{
    "Keyword": [
        ":-", 
        "case", 
        "continue", 
        "do", 
        "done", 
        "elif", 
        "else", 
        "esac", 
        "fi", 
        "for", 
        "function", 
        "if", 
        "return", 
        "select", 
        "then", 
        "until", 
        "while"
    ]
}