{
    "Keyword": [
        "call", 
        "cd", 
        "choice", 
        "cls", 
        "cmdextversion", 
        "defined", 
        "del", 
        "deltree", 
        "do", 
        "echo", 
        "else", 
        "endlocal", 
        "errorlevel", 
        "exist", 
        "for", 
        "goto", 
        "if", 
        "md", 
        "off", 
        "on", 
        "pause", 
        "set", 
        "setlocal", 
        "shift"
    ]
}