{
    "Keyword": [
        ";", 
        "ALIEN:", 
        "CONSTANT:", 
        "ERROR:", 
        "FUNCTION:", 
        "INSTANCE:", 
        "MIXIN:", 
        "SINGLETON:", 
        "SINGLETONS:", 
        "SLOT:", 
        "STRUCT:", 
        "SYMBOL:", 
        "SYMBOLS:", 
        "SYNTAX:", 
        "TYPEDEF:", 
        "deprecated", 
        "final", 
        "flushable", 
        "foldable", 
        "inline", 
        "recursive"
    ], 
    "Namespace": [
        "<PRIVATE", 
        "ALIAS:", 
        "DEFER:", 
        "FORGET:", 
        "POSTPONE:", 
        "PRIVATE>"
    ]
}