{
    "Constant": [
        "false", 
        "iota", 
        "nil", 
        "true"
    ], 
    "Declaration": [
        "chan", 
        "const", 
        "func", 
        "interface", 
        "map", 
        "struct", 
        "type", 
        "var"
    ], 
    "Keyword": [
        "break", 
        "case", 
        "continue", 
        "default", 
        "defer", 
        "else", 
        "fallthrough", 
        "for", 
        "go", 
        "goto", 
        "if", 
        "range", 
        "return", 
        "select", 
        "switch"
    ], 
    "Namespace": [
        "import", 
        "package"
    ], 
    "Type": [
        "bool", 
        "byte", 
        "complex128", 
        "complex64", 
        "error", 
        "float", 
        "float32", 
        "float64", 
        "int", 
        "int16", 
        "int32", 
        "int64", 
        "int8", 
        "rune", 
        "string", 
        "uint", 
        "uint16", 
        "uint32", 
        "uint64", 
        "uint8", 
        "uintptr"
    ]
}