{
    "Constant": [
        "false", 
        "nil", 
        "true"
    ], 
    "Keyword": [
        "and", 
        "break", 
        "class", 
        "do", 
        "else", 
        "elseif", 
        "export", 
        "extends", 
        "for", 
        "from", 
        "if", 
        "import", 
        "in", 
        "not", 
        "or", 
        "return", 
        "super", 
        "switch", 
        "then", 
        "using", 
        "when", 
        "while", 
        "with"
    ]
}