{
    "Keyword": [
        "as", 
        "assert", 
        "break", 
        "continue", 
        "del", 
        "elif", 
        "else", 
        "except", 
        "exec", 
        "finally", 
        "for", 
        "from", 
        "global", 
        "if", 
        "lambda", 
        "pass", 
        "print", 
        "raise", 
        "return", 
        "try", 
        "while", 
        "with", 
        "yield"
    ], 
    "Namespace": [
        "as"
    ]
}