{
    "Keyword": [
        "and", 
        "as", 
        "begin", 
        "css", 
        "database", 
        "db", 
        "do", 
        "else", 
        "end", 
        "external", 
        "forall", 
        "if", 
        "import", 
        "match", 
        "package", 
        "parser", 
        "rec", 
        "server", 
        "then", 
        "type", 
        "val", 
        "with", 
        "xml_parser"
    ]
}