{
    "Constant": [
        "e", 
        "epsilon", 
        "log10", 
        "log2", 
        "negative_epsilon", 
        "negative_infinity", 
        "not_a_number", 
        "pi", 
        "positive_infinity", 
        "sqrt2"
    ], 
    "Reserved": [
        "T", 
        "else", 
        "false", 
        "for", 
        "if", 
        "in", 
        "lower", 
        "print", 
        "repeat", 
        "then", 
        "true", 
        "until", 
        "upper", 
        "while"
    ], 
    "Type": [
        "corr_matrix", 
        "cov_matrix", 
        "int", 
        "matrix", 
        "ordered", 
        "positive_ordered", 
        "real", 
        "row_vector", 
        "simplex", 
        "vector"
    ]
}