{
    "Keyword": [
        ":-", 
        "breaksw", 
        "case", 
        "continue", 
        "default", 
        "else", 
        "end", 
        "endif", 
        "endsw", 
        "foreach", 
        "goto", 
        "if", 
        "switch", 
        "then", 
        "while"
    ]
}